name 'proteon-tomcat'
version '0.1.0'

author 'Sander Bilo'
license 'Apache'
project_page 'https://github.com/Proteon/puppet-tomcat'
source 'git://github.com/Proteon/puppet-tomcat.git'
summary ''
description ''
dependency 'proteon/java', '>=0.1'
