name 'proteon-tomcat'
version '0.1.4'

author 'Sander Bilo'
license 'Apache'
project_page 'https://github.com/Proteon/puppet-tomcat'
source 'git://github.com/Proteon/puppet-tomcat.git'
summary ''
description ''
dependency 'ripienaar/concat', '>=0.2.0'
dependency 'klangrud/profile_d', '>=0.0.1'
dependency 'proteon/maven', '>=1.0.1'
